[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
xxx = "25rttwt9tDmwy47hBVGCShJGA68pCBCYhrcDbJcu5k31"

[programs.localnet]
anchor_number = "26pLVQG6CJybjhbtFJbmcmAwqUVuFYmSso1yMFGVnW2E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sainy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
